program: main.py
method: grid
metric:
  goal: maximize
  name: test accuracy
parameters:
  project_name:
    value: "CL_Visualization"
  dataset:
    value: "CIFAR10"
  scenario_name:
    value: "Disjoint"
  opt_name:
    value: "Adam"
  batch_size:
    value: 8
  lr:
    values: [0.001]
  num_tasks:
    value: 5
  nb_epochs:
    value: 50
  name_algo:
    values: ["rehearsal"]
  nb_samples_rehearsal_per_class:
    value: 100
  OutLayer:
    values: [ 'Linear', 'WeightNorm' ]
  masked_out:
    values: [ "None", "group"]
  replay_balance:
    values: [0.01, 0.1, 0.5, 1.0]
  seed:
    values: [0, 1, 2]

command:
  - python
  - ${program}
  - "--sweep"
  - "--fast"
  - "--sweeps_HPs"
  - "--reset_opt"
  - ${args}