program: main.py
method: grid
metric:
  goal: maximize
  name: test accuracy
parameters:
  dataset:
    value: "CIFAR10"
  scenario_name:
    value: "Disjoint"
  num_tasks:
    value: 5
  nb_epochs:
    value: 25
  OutLayer:
    values: ["MeanLayer", "WeightNorm"]
  name_algo:
    value: "baseline"
  masked_out:
    value: "multi-head"
  pretrained_on:
    value: "CIFAR100"
  seed:
    values: [0,1,2,3,4]

command:
  - python
  - ${program}
  - "--sweep"
  - "--lr=0.1"
  - "--fast"
  - "--test_label"
  - "--reset_opt"
  - ${args}
