program: main.py
method: grid
metric:
  goal: maximize
  name: test accuracy
parameters:
  dataset:
    values: ["OxfordPet", "OxfordFlower102"]
  scenario_name:
    value: "Disjoint"
  num_tasks:
    value: 10
  nb_epochs:
    value: 25
  OutLayer:
    values: ["MeanLayer", "WeightNorm", "Linear"]
  architecture:
    values: ["resnet", "alexnet", "vgg", "googlenet"]
  name_algo:
    value: "baseline"
  masked_out:
    value: "multi-head"
  pretrained_on:
    value: "ImageNet"
  seed:
    values: [0,1,2,3,4]

command:
  - python
  - ${program}
  - "--sweep"
  - "--lr=0.1"
  - "--fast"
  - "--test_label"
  - "--reset_opt"
  - "--keep_task_order"
  - ${args}
