program: main.py
method: grid
metric:
  goal: maximize
  name: test accuracy task 5
parameters:
  dataset:
    value: "CIFAR10"
  scenario_name:
    value: "SpuriousFeatures"
  num_tasks:
    value: 5
  nb_epochs:
    value: 25
  name_algo:
    value: "rehearsal"
  spurious_corr:
    # We test only with 0.75, values: [0.25, 0.5, 0.75, 1.0]
    value: 0.75
  seed:
    values: [0,1]
  nb_samples_rehearsal_per_class:
    values: [ 10, 50, 100, 500, 1000 ]

command:
  - python
  - ${program}
  - "--sweep"
  - "--sweeps_HPs"
  - "--fast"
  - ${args}