program: main.py
method: grid
metric:
  goal: maximize
  name: test accuracy task 10
parameters:
  dataset:
    value: "CIFAR10"
  scenario_name:
    value: "SpuriousFeatures"
  num_tasks:
    value: 10
  nb_epochs:
    value: 25
  name_algo:
    values: ['ewc_diag', 'ewc_kfac']
  importance:
    values: [1e-1, 1e0, 1e1, 1e2, 1e3, 1e4, 1e5]
  spurious_corr:
    value: 1.00
  support:
    value: 1.0
  seed:
    values: [0, 1]

command:
  - python
  - ${program}
  - "--sweep"
  - "--fast"
  - "--sweeps_HPs"
  - ${args}